### ISSUE TITLE
SegFault with Csound 6.07.0

### ISSUE THREAD

**Issue by biggybass** [digithree/leap-into#1]
When using any of the leap opcodes in the latest version of Csound, CsoundQT crashes. When running Csound within the terminal the only error that is returned is csound command: Segmentation fault. I am using OSX el capitan 10.11.6

**Comment by digithree** [comment]
Thanks @biggybass I'll look into this when I get a change

**Comment by digithree** [comment]
I've rebuilt the library slightly ahead of the version you have quoted having a problem with, in OSX Sierra 10.12.1 (latest), and for Csound 6.08, with Leap SDK 2.3.1

Hopefully this works for you. It shouldn't be too hard to build on your own machine if you still get a seg fault, I can update you with instructions. It's not super super friendly (will hopefully get a chance to make better local build settings) but doable with a few tweaks.

Will close this unless I hear otherwise. Btw the binary is in the dist folder, most up to date Leap lib binary in lib folder.
